version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "pg"
      POSTGRES_USER: "Shili"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    container_name: minio
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "rootpassword"
      MINIO_USE_SSL: "false"
      MINIO_DEFAULT_BUCKETS: "mybucket"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:



#  localstack:
#    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
#    image: localstack/localstack
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    environment:
#      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
#      - DEBUG=${DEBUG:-0}
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"