// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package courses_repo

import (
	"context"
)

type Querier interface {
	AddCourseBasicInfo(ctx context.Context, arg *AddCourseBasicInfoParams) error
	AddCourseGoals(ctx context.Context, arg *AddCourseGoalsParams) error
	CreateCourseBase(ctx context.Context, arg *CreateCourseBaseParams) error
	GetEightCoursesShort(ctx context.Context) ([]*GetEightCoursesShortRow, error)
}

var _ Querier = (*Queries)(nil)
