// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users_repo

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (int32, error)
	GetHasUserTriedInstructor(ctx context.Context, id int32) (*bool, error)
	GetUserByEmailAndHashedPassword(ctx context.Context, arg *GetUserByEmailAndHashedPasswordParams) (*HumanResourcesUser, error)
	GetUserByID(ctx context.Context, id int32) (*HumanResourcesUser, error)
	GetUsers(ctx context.Context) ([]*HumanResourcesUser, error)
	UpdateAvatar(ctx context.Context, arg *UpdateAvatarParams) error
	UpdateHasUserTriedInstructor(ctx context.Context, id int32) error
	UpdateTeachingExperience(ctx context.Context, arg *UpdateTeachingExperienceParams) error
	UpdateUser(ctx context.Context, arg *UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
