// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package users_repo

import (
	"context"
)

const addTeachingExperience = `-- name: AddTeachingExperience :exec
INSERT INTO human_resources.instructors_info (user_id, has_video_knowledge, current_audience_count, has_previous_experience) VALUES ($1, $2, $3, $4)
`

type AddTeachingExperienceParams struct {
	UserID                int32
	HasVideoKnowledge     string
	CurrentAudienceCount  string
	HasPreviousExperience string
}

func (q *Queries) AddTeachingExperience(ctx context.Context, arg *AddTeachingExperienceParams) error {
	_, err := q.db.Exec(ctx, addTeachingExperience,
		arg.UserID,
		arg.HasVideoKnowledge,
		arg.CurrentAudienceCount,
		arg.HasPreviousExperience,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO human_resources.users (full_name, email,description, password_hashed, phone_number) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateUserParams struct {
	FullName       string
	Email          string
	Description    *string
	PasswordHashed string
	PhoneNumber    string
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Description,
		arg.PasswordHashed,
		arg.PhoneNumber,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getHasUserTriedInstructor = `-- name: GetHasUserTriedInstructor :one
SELECT has_user_tried_instructor from human_resources.users WHERE id = $1
`

func (q *Queries) GetHasUserTriedInstructor(ctx context.Context, id int32) (*bool, error) {
	row := q.db.QueryRow(ctx, getHasUserTriedInstructor, id)
	var has_user_tried_instructor *bool
	err := row.Scan(&has_user_tried_instructor)
	return has_user_tried_instructor, err
}

const getUserByEmailAndHashedPassword = `-- name: GetUserByEmailAndHashedPassword :one
SELECT id, full_name, description, avatar, email, password_hashed, created_at, updated_at, has_user_tried_instructor, phone_number from human_resources.users WHERE email = $1 AND password_hashed = $2
`

type GetUserByEmailAndHashedPasswordParams struct {
	Email          string
	PasswordHashed string
}

func (q *Queries) GetUserByEmailAndHashedPassword(ctx context.Context, arg *GetUserByEmailAndHashedPasswordParams) (*HumanResourcesUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndHashedPassword, arg.Email, arg.PasswordHashed)
	var i HumanResourcesUser
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.Avatar,
		&i.Email,
		&i.PasswordHashed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasUserTriedInstructor,
		&i.PhoneNumber,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, description, avatar, email, password_hashed, created_at, updated_at, has_user_tried_instructor, phone_number from human_resources.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (*HumanResourcesUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i HumanResourcesUser
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.Avatar,
		&i.Email,
		&i.PasswordHashed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasUserTriedInstructor,
		&i.PhoneNumber,
	)
	return &i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, full_name, description, avatar, email, password_hashed, created_at, updated_at, has_user_tried_instructor, phone_number from human_resources.users
`

func (q *Queries) GetUsers(ctx context.Context) ([]*HumanResourcesUser, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*HumanResourcesUser
	for rows.Next() {
		var i HumanResourcesUser
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.Avatar,
			&i.Email,
			&i.PasswordHashed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasUserTriedInstructor,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvatar = `-- name: UpdateAvatar :exec
UPDATE human_resources.users SET avatar = $1 WHERE id = $2
`

type UpdateAvatarParams struct {
	Avatar []byte
	ID     int32
}

func (q *Queries) UpdateAvatar(ctx context.Context, arg *UpdateAvatarParams) error {
	_, err := q.db.Exec(ctx, updateAvatar, arg.Avatar, arg.ID)
	return err
}

const updateHasUserTriedInstructor = `-- name: UpdateHasUserTriedInstructor :exec
UPDATE human_resources.users SET has_user_tried_instructor = true WHERE id = $1
`

func (q *Queries) UpdateHasUserTriedInstructor(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateHasUserTriedInstructor, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE human_resources.users SET full_name = $1, email = $2, description = $3, phone_number = $4 WHERE id = $5
`

type UpdateUserParams struct {
	FullName    string
	Email       string
	Description *string
	PhoneNumber string
	ID          int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.FullName,
		arg.Email,
		arg.Description,
		arg.PhoneNumber,
		arg.ID,
	)
	return err
}
