// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users_repo

import (
	"context"
)

type Querier interface {
	GetUsers(ctx context.Context) ([]*GetUsersRow, error)
}

var _ Querier = (*Queries)(nil)
