// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users_repo

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (int32, error)
	GetUserByEmailAndHashedPassword(ctx context.Context, arg *GetUserByEmailAndHashedPasswordParams) (*HumanResourcesUser, error)
	GetUserByID(ctx context.Context, id int32) (*HumanResourcesUser, error)
	GetUsers(ctx context.Context) ([]*HumanResourcesUser, error)
}

var _ Querier = (*Queries)(nil)
