// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package courses

import (
	"context"
)

type Querier interface {
	AddCourseBasicInfo(ctx context.Context, arg *AddCourseBasicInfoParams) (int32, error)
	AddCourseGoals(ctx context.Context, arg *AddCourseGoalsParams) (int32, error)
	ApproveCourse(ctx context.Context, id int32) (int32, error)
	CreateCourseBase(ctx context.Context, arg *CreateCourseBaseParams) (int32, error)
	GetAllDraftCourses(ctx context.Context) ([]*HumanResourcesCourse, error)
	GetAllPendingCourses(ctx context.Context) ([]*HumanResourcesCourse, error)
	GetAllReadyCourses(ctx context.Context) ([]*HumanResourcesCourse, error)
	GetUserCourses(ctx context.Context, userID int32) ([]*GetUserCoursesRow, error)
	// Вставляет лекцию в таблицу lectures и соответствующую запись в таблицу courses_lectures
	InsertLectureAndCourseLecture(ctx context.Context, arg *InsertLectureAndCourseLectureParams) (*InsertLectureAndCourseLectureRow, error)
	InsertLectureTitleAndDescription(ctx context.Context, arg *InsertLectureTitleAndDescriptionParams) (int32, error)
	RejectCourse(ctx context.Context, id int32) (int32, error)
	RemoveLecture(ctx context.Context, id int32) (int32, error)
	RemoveLectureFromCourse(ctx context.Context, id int32) (int32, error)
	SearchCoursesByTitle(ctx context.Context, title string) ([]*SearchCoursesByTitleRow, error)
	SendCourseToCheck(ctx context.Context, id int32) (int32, error)
	UpdateCourseAvatar(ctx context.Context, arg *UpdateCourseAvatarParams) (*string, error)
	UpdateCoursePreviewVideo(ctx context.Context, arg *UpdateCoursePreviewVideoParams) (*string, error)
	UpdateLectureTitle(ctx context.Context, arg *UpdateLectureTitleParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
